// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto.proto at 4:1
package io.landerlyoung.github.kproto.performance.serialtest.wire;

import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum ItemType implements WireEnum {
  TEXT(0),

  PICTURE(1),

  BINARY(100);

  public static final ProtoAdapter<ItemType> ADAPTER = ProtoAdapter.newEnumAdapter(ItemType.class);

  private final int value;

  ItemType(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ItemType fromValue(int value) {
    switch (value) {
      case 0: return TEXT;
      case 1: return PICTURE;
      case 100: return BINARY;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }
}
