// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto.proto at 14:1
package io.landerlyoung.github.kproto.performance.serialtest.wire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PictureItem extends Message<PictureItem, PictureItem.Builder> {
  public static final ProtoAdapter<PictureItem> ADAPTER = new ProtoAdapter_PictureItem();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_PICTUREURL = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String pictureUrl;

  public PictureItem(String pictureUrl) {
    this(pictureUrl, ByteString.EMPTY);
  }

  public PictureItem(String pictureUrl, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.pictureUrl = pictureUrl;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.pictureUrl = pictureUrl;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PictureItem)) return false;
    PictureItem o = (PictureItem) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(pictureUrl, o.pictureUrl);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (pictureUrl != null ? pictureUrl.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (pictureUrl != null) builder.append(", pictureUrl=").append(pictureUrl);
    return builder.replace(0, 2, "PictureItem{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PictureItem, Builder> {
    public String pictureUrl;

    public Builder() {
    }

    public Builder pictureUrl(String pictureUrl) {
      this.pictureUrl = pictureUrl;
      return this;
    }

    @Override
    public PictureItem build() {
      return new PictureItem(pictureUrl, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PictureItem extends ProtoAdapter<PictureItem> {
    ProtoAdapter_PictureItem() {
      super(FieldEncoding.LENGTH_DELIMITED, PictureItem.class);
    }

    @Override
    public int encodedSize(PictureItem value) {
      return (value.pictureUrl != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.pictureUrl) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PictureItem value) throws IOException {
      if (value.pictureUrl != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.pictureUrl);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PictureItem decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.pictureUrl(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PictureItem redact(PictureItem value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
