// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto.proto at 10:1
package io.landerlyoung.github.kproto.performance.serialtest.wire;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class TextItem extends Message<TextItem, TextItem.Builder> {
  public static final ProtoAdapter<TextItem> ADAPTER = new ProtoAdapter_TextItem();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_TEXT = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String text;

  public TextItem(String text) {
    this(text, ByteString.EMPTY);
  }

  public TextItem(String text, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.text = text;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.text = text;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TextItem)) return false;
    TextItem o = (TextItem) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(text, o.text);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (text != null ? text.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (text != null) builder.append(", text=").append(text);
    return builder.replace(0, 2, "TextItem{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TextItem, Builder> {
    public String text;

    public Builder() {
    }

    public Builder text(String text) {
      this.text = text;
      return this;
    }

    @Override
    public TextItem build() {
      return new TextItem(text, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TextItem extends ProtoAdapter<TextItem> {
    ProtoAdapter_TextItem() {
      super(FieldEncoding.LENGTH_DELIMITED, TextItem.class);
    }

    @Override
    public int encodedSize(TextItem value) {
      return (value.text != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.text) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TextItem value) throws IOException {
      if (value.text != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TextItem decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.text(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TextItem redact(TextItem value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
